spring:
  application:
    name: Salms

  security:
    basicauth:
      enabled: true
      username: client
      password: client-password

    user:
      name: client
      password: client-password

  datasource:
    url: jdbc:postgresql://localhost:5432/salon_management
    username: valentine.waweru
    password: password

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: "optional:configserver:"

server:
  port: 8090
